<?php

    // @Author: Vasilis Neris
    // @contact: vasilis.neris@gmail.com
    // @Description: Skroutz Analytics
    
    // Skytech Skroutz Analytics is free software: you can redistribute it and/or modify
    // it under the terms of the GNU General Public License as published by
    // the Free Software Foundation, either version 3 of the License, or
    // (at your option) any later version.

    // Skytech Skroutz Analytics is distributed in the hope that it will be useful,
    // but WITHOUT ANY WARRANTY; without even the implied warranty of
    // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    // GNU General Public License for more details.

    // You should have received a copy of the GNU General Public License
    // along with this code.  If not, see <https://www.gnu.org/licenses/>.

    
?>

<?php 
$enabled = $block->getStoreConfig('skroutz_analytics/script/enable');

if ($enabled) {
    echo $script = $block->getStoreConfig('skroutz_analytics/script/tracking');
}

?>

